= Marketplace deploy description

This page contains instructions for creating a production-grade deployment of Aqua CSP (Cloud native Security Platform) on an Amazon ECS cluster.
For high availability, you must deploy Aqua on 2 availability zones (AZs).

These instructions are applicable to all versions of Aqua CSP.

Your deployment will create these services:
 - Aqua Server, deployed with an Amazon Application Load Balancer
 - Aqua Database, created on a new Amazon RDS instance, which includes 7 days of rolling backups
 - Aqua Gateways (2), each on a separate subnet, deployed with a Classic Load Balancer
 - Aqua Enforcers (1 deployed on each host in your cluster, via a DaemonSet)

In addition, it will create an IAM role for giving the Aqua Server access to ECR (Elastic Container Registry).

== Requirements

* An ECS cluster with at least 2 hosts
* A VPC with at least 2 subnets connected to the ECS cluster

== Deployment CloudFormation Management Console

. Ensure that your AWS region is set to where you want to deploy Aqua CSP.
. Click "Next".
. Set or modify any of the parameters (per the explanations provided).
. Click "Next" to create the stack.

It will typically require up to 20 minutes for Aqua CSP to be deployed.
When completed, you can obtain the DNS name of the Aqua Server UI from the console output, under key name `AquaConsole`.

parameters description:

----
AquaConsoleAccess = The IP address or range that may be used to access the Aqua Console (Server UI) (example: x.x.x.x/32)  
BatchInstallToken = Any string; it will be used as the token in the Aqua Enforcer Install command 
EcsClusterName = Existing ECS cluster name 
EcsInstanceSubnets = Select at least 2 subnets on which you want Aqua to be deployed  
EcsSecurityGroupId = The security group assigned to the ECS cluster during cluster creation 
MultiAzDatabase = Set to true to enable deployment in multiple Availability Zones 
RdsInstanceClass = Set the EC2 instance class for the RDS DB instance 
RdsInstanceName = Set the name of the Aqua DB, e.g., AquaDB 
RdsMasterPassword = The master password for the RDS instance. This password must contain from 8-128 printable ASCII characters except for @, /,  or ". 
RdsMasterUsername = The master username for the RDS instance 
RdsStorage = Set the size (GB) of the RDS DB instance  
VpcCidr = For use by load balancer service polling. Enter the VPC CIDR (example: 10.0.0.0/16) 
VpcId = The VpcId to deploy into 
LbSubnets = Select external subnets if you need Internet access  
----

It will typically require up to 20 minutes for your stack to be created and deployed.
When completed, you can obtain the DNS name of the Aqua Server UI from the console output, under key name `AquaConsole`.